# # Configuración de Base de Datos
# spring.datasource.url=jdbc:postgresql://localhost:5432/artesanias_cuero
# spring.datasource.username=postgres
# spring.datasource.password=diego(1996)1

# # JPA / Hibernate
# spring.jpa.hibernate.ddl-auto=none
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# # Puerto del servidor
# server.port=8080